### ISSUE TITLE
Pure Wayland apps have blurry text

### ISSUE THREAD

**Issue by tjikini** [Immington-Industries/way-cooler#198]
![](https://i.imgsafe.org/acac17f62a.png)
Left is way-cooler and right is sway.

```
Screen 0: minimum 320 x 200, current 1366 x 768, maximum 8192 x 8192
XWAYLAND0 connected 1360x768+0+0 340mm x 190mm
   1360x768      59.80*+
```

Archlinux
wlc 0.0.7
sway 0.11.0
way-cooler 0.4.1

**Comment by Timidger** [comment]
Was this same resolution chosen for sway as well? And you ran both sway and way-cooler in the same environment? (e.g: both from the same login manager, both embedded in an X instance with the same screen real-estate, or both from the same TTY)? I find it strange that it chose 1360x768 when it says the current is 1366x768.

Perhaps Sway is doing some magic incantation that I do not know about, but wlc is the one that chooses the resolution to render at ([which is not yet controllable, sadly](https://github.com/Cloudef/wlc/issues/37)). The GUI toolkits / Xwayland should be the one handling the rendering, but if the issue was there it would be present in sway too and it's not...

The only thing that we don't handle that sway does is the output resolution changing and multi-output, which is the only thing I can think of that _might_ cause this problem.

**Comment by tjikini** [comment]
Now notice that this issue affects only GDK apps, QT fonts is fine.

`xrandr` output are identical in sway, way-cooler and gnome-session

 > And you ran both sway and way-cooler in the same environment?
Yes

**Comment by Timidger** [comment]
> "Pure" Wayland apps are blurry.

Ahh, now we are getting some where. I can reproduce the issue with `weston-terminal`, funny I didn't notice it before.

**Comment by Timidger** [comment]
Asked for help on the #orbment IRC channel (which seems to double for questions about wlc as well). I was able to affect the readability of the font by modifying the `GDK_DPI_SCALE` variable. E.g, setting it to `2` made the text no longer blurry (but obviously very, very big).

Another interesting thing that caused it to no longer occur was trying to make the app "fullscreen" with f11. We don't handle that properly yet, but we still set the relevant bit on the window. This causes the client side borders to disappear (since that's what most GUI toolkits want to do) but also causes the text to become less blurry (and stay the same, normal size).

**Comment by Timidger** [comment]
Found a fix, thanks to those lovely people: views have the "maximized" bit set in Sway, which is probably what we need to do to fix this.
