### ISSUE TITLE
Is multi-seat / multi-pointer / multi-focus supported or planned?

### ISSUE THREAD

**Issue by Ape** [Immington-Industries/way-cooler#235]
I'm looking for a tiling window manager for Wayland that supports multi-seat / multi-pointer / multi-focus features ([example](https://www.youtube.com/watch?v=WO2L_ihO_rI)). Are these features supported or planned for Way Cooler?

Mainly I am looking support for a concept of multi-focus where different sets of pointers and keyboards would have their own focus (perhaps visually color coded on the windows). Wayland itself would allow the features.

**Comment by Timidger** [comment]
It's not something I had considered in the short term (I haven't even got around to implementing multi-output, though that should change in the near future).

However, I wouldn't say it's beyond the scope of the project. Depending on how popular such a feature is, it could be added to the 1.0 road map.

Taking a quick look at the wlc bindings ([here](https://github.com/Cloudef/wlc/blob/master/include/wlc/wlc.h#L242) are the relevant bits), it looks like such a feature is experimental. @cloudef, would there need to be any changes to wlc to further support this feature or are the current bindings sufficient. From a quick peek [at the relevant libinput docs](https://wayland.freedesktop.org/libinput/doc/1.2.1/libinput_8h_source.html) it seems ready enough.

**Comment by Cloudef** [comment]
I don't think it's possible at time, especially multi-focus.

**Comment by Timidger** [comment]
That's a shame. 

Looking at the wlc api a bit closer, is there even a way to send keyboard input to the non focused view @cloudef? There seems to be a lot of assumptions around a single view being focused and being modified by a single keyboard. 

@ape, since wlc doesn't support this (and probably won't for a while), I suggest you look into tiling window managers that are implemented either using libweston or as a weston plugin.

**Comment by Cloudef** [comment]
Internally wlc can do it, externally not. It would need removing the abstraction and exposing the internals. However that's not the only problem. Multi-focus brings lots of problems with applications (especially X11 ones) that don't expect it.

**Comment by Ape** [comment]
I have used multi-pointer X before. Yes, it may cause some weird behavior with some applications when using features like drag-and-drop, but usually it works just fine. I wouldn't say that the occasional application bugs are that bad.

I understand that multi-focus would require quite a bit of refactoring / redesigning on the API, but I'd still like to think it's worth it. I am not saying that every WM should implement multi-focus, but I am hoping that at least some decent WMs support it in the future.

**Comment by Timidger** [comment]
A lot of the current API is built around that assumption (e.g active view, active output (what if multiple seats are operating on different outputs), pointer, etc.). It can be changed of course, especially because wlc is still considered unstable, but it would probably require quite a few coordinated patches to get fixed.

I'm going to go ahead and close this issue, since Way Cooler currently can't support this feature.
