### ISSUE TITLE
What is it with Rust crates never ever caring to add git tags on the repo?

### ISSUE THREAD

**Issue by vinipsmaker** [Immington-Industries/way-cooler#49]
Hey, it'd be useful for me to package this software for ArchLinux if git tags are provided. If you care about preserving the history of the project, tags are useful too.

**Comment by SnirkImmington** [comment]
Thank your for offering to port to AUR! I think release tags slipped past us in our rush to get things together to announce (we're only 0.3 anyway). I assume most other Rust crates don't have git tags because their authors prefer to stay indefinitely pre-1.0 and just install through cargo. 

We also need to figure out a build script before we're for platform distribution. Specifically,
* Wayland depdendencies
* Installing [wlc](https://github.com/Cloudef/wlc)
* Installing other Rust dependencies (they are statically linked in the binary, I assume just running `cargo build` when we're building from source)
* Move our init file to `/etc/way-cooler` or `.config/way-cooler`
* Later, we'll have some Lua utils to move to `/usr/local` or something

We also need to update rustwlc to the latest wlc version (been too busy with way-cooler).

@Timidger anything I'm missing?

**Comment by Timidger** [comment]
Yep, looks like all of the dependencies. @vinipsmaker, I went ahead and added tagged the 0.3 release, so you should be all set to make a PKGBULD for Arch.

**Comment by vinipsmaker** [comment]
Thanks guys.

Packages are up:

- https://aur.archlinux.org/packages/way-cooler/
- https://aur.archlinux.org/packages/way-cooler-git/
