### ISSUE TITLE
It crashes when mpv closes

### ISSUE THREAD

**Issue by vinipsmaker** [Immington-Industries/way-cooler#56]
Just open any video (`mpv -vo=wayland video_file`) and wait until finishes (or press `q`) and `way-cooler` crashes. If you cannot reproduce the issue just with just this info, I can look more into it (share video file, get logs, and so on).

**Comment by Timidger** [comment]
Yikes, I can reproduce and it looks like a segfault. It most likely has to with interfacing with wlc, somehow we are using a view handle after it has been deleted. I also noticed that the scaling factor went back down to 0.5 when I logged in on mine, which is new to rustwlc and not something we have made changes to in Way Cooler, so it could perhaps be that. 

We'll look into this, can you reproduce this on other programs other than mpv? I assume it has to do with some special way mpv closes that's causing this issue.

**Comment by vinipsmaker** [comment]
> We'll look into this, can you reproduce this on other programs other than mpv?

From the few programs I tested, `mpv` was the only naughty one.

**Comment by Timidger** [comment]
Can reproduce on release build, isn't validation checks on the tree causing the problem

**Comment by Timidger** [comment]
Stepping through the stack frame, it looks like it was a double free on the handle, somehow mpv is closing itself and then we respond to the event by trying to close it as well.

It looks like for the most part that when a program has already closed itself (e.g the `view_destroyed` callback is triggered), calling `view.close` on that view is technically undefined behaviour since it's not guaranteed to point to a valid view. 

The fix can be complete once we have the kill window command working again, since I can't test when I actually have to call `view.close` without, since in all other causes it's the window telling Way Cooler it's closing which will trigger this undefined behaviour.

Blocking until #57 is resolved.

**Comment by vinipsmaker** [comment]
Oh, retrorach will also cause way-cooler to crash when I try to open some game.

**Comment by vinipsmaker** [comment]
Perfect. `mpv` and `retroarch` are working sound now.
